Flowpack:
  SchemaOrg:
    NodeTypes:
      schemas:
        source: 'resource://Flowpack.SchemaOrg.NodeTypes/Private/Schema/All.json'
        storagePath: '%FLOW_PATH_DATA%Persistent/FlowpackSchemaOrgNodeTypes'
